# Find more information on toml format here:  https://github.com/toml-lang/toml

modLoader="javafml"
loaderVersion="${forge_version_range}"
license="${mod_license}"
#issueTrackerURL=""

[[mods]]
   modId="${mod_id}"
   version="${mod_version}"
   displayName="${mod_name}"
   #updateJSONURL=""  # See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
   #displayURL=""
   #logoFile=""
   #credits=""
   authors="${mod_authors}"
   # Display Test controls the display for your mod in the server connection screen
   # MATCH_VERSION means that your mod will cause a red X if the versions on client and server differ. This is the default behaviour and should be what you choose if you have server and client elements to your mod.
   # IGNORE_SERVER_VERSION means that your mod will not cause a red X if it's present on the server but not on the client. This is what you should use if you're a server only mod.
   # IGNORE_ALL_VERSION means that your mod will not cause a red X if it's present on the client or the server. This is a special case and should only be used if your mod has no server component.
   # NONE means that no display test is set on your mod. You need to do this yourself, see IExtensionPoint.DisplayTest for more information. You can define any scheme you wish with this value.
   #displayTest="MATCH_VERSION"
   description='''${mod_description}'''

[[dependencies.${mod_id}]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   # BEFORE - This mod is loaded BEFORE the dependency
   # AFTER - This mod is loaded AFTER the dependency
   ordering="NONE"
   side="BOTH" # Side: BOTH, CLIENT, or SERVER

[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies.${mod_id}]]
    modId="tfc"
    mandatory=true
    versionRange="${tfc_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="cloth_config"
    mandatory=false
    versionRange="${cloth_version_range}"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
   modId="create"
   mandatory=false
   versionRange="${create_version_range}"
   ordering="AFTER"
   side="BOTH"
